# Generated by Django 4.1 on 2023-03-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmployeeApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employment_status",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="manager_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="employee",
            name="marital_status",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="performance_score",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(max_length=30),
        ),
    ]
